name: Build

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          swift: '5.8'
        - os: macos-latest
          swift: '5.10'

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install native dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y libavahi-compat-libdnssd-dev
    - name: Install Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build
    - name: Test
      run: swift test
